### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by ErickN13** [MinicraftPlus/minicraft-plus-revived#578] opened 2023-10-23 12:43 UTC
It would be better to create a version for Android, as not everyone has a computer with Java.

**Comment by ErickN13** [comment] 2023-10-23 12:54
> You already know this is planned...
> https://github.com/MinicraftPlus/minicraft-plus-revived/issues/571
> https://github.com/MinicraftPlus/minicraft-plus-revived/issues/469

But is the MinicraftPlusRevived development team already working on developing an Android version?

**Comment by maxkratt** [comment] 2023-10-23 15:29
> @maxkratt I was looking at one of your repositories, and I found something called UnityCraft for Android, I installed it and UnityCraft is very cool, but it's a bit stuck and full of bugs, but if you go there, fix it These Bugs and Make the Game More Optimized, Then Everything is Ready, We Will Now Have a Minicraft for Android

I abandoned working on it quite some time ago. Many bugs were fixed that haven't been released yet and most importantly there aren't mobs in the game yet. I was using it as a project to learn multiplayer coding and if I were to work on it again I'd probably start from scratch.

**Comment by ErickN13** [comment] 2023-10-23 15:58
> > @maxkratt I was looking at one of your repositories, and I found something called UnityCraft for Android, I installed it and UnityCraft is very cool, but it's a bit stuck and full of bugs, but if you go there, fix it These Bugs and Make the Game More Optimized, Then Everything is Ready, We Will Now Have a Minicraft for Android
> 
> I abandoned working on it quite some time ago. Many bugs were fixed that haven't been released yet and most importantly there aren't mobs in the game yet. I was using it as a project to learn multiplayer coding and if I were to work on it again I'd probably start from scratch.

But is the MinicraftPlusRevived development team already working on developing an Android version?

**Comment by maxkratt** [comment] 2023-10-23 16:03
It's not high on the development list at the moment I believe.
You could always take part and help with it though.

**Comment by ErickN13** [comment] 2023-10-23 16:07
> It's not high on the development list at the moment I believe.
> You could always take part and help with it though.

Sorry, I can't help, because I don't know any programming language so I can program an Android version of MinicraftPlusRevived

**Comment by BenCheung0422** [comment] 2023-10-24 04:02
Duplicate of #469

**Closed** 2023-10-24 04:02 UTC
