### ISSUE TITLE
mouse not supported

### ISSUE THREAD

**Issue by CodingPro1234** [MinicraftPlus/minicraft-plus-revived#484] opened 2023-05-21 19:26 UTC
in the video below i am clicking... but nothing happens
video:   

https://github.com/MinicraftPlus/minicraft-plus-revived/assets/113947915/9727d99b-0c12-4534-b448-cd09df0a495b

**Comment by Makkkkus** [comment] 2023-05-21 19:30
This is not a bug and has been an important aspect of the game since the original. Also a duplicate of #367.

**Closed by Makkkkus** 2023-05-21 19:30 UTC
Labels: Bug
