### ISSUE TITLE
Menu buttons bug!

### ISSUE THREAD

**Issue by VaILI12** [MinicraftPlus/minicraft-plus-revived#563] opened 2023-08-25 15:32 UTC
![что](https://github.com/MinicraftPlus/minicraft-plus-revived/assets/143204276/81f2127c-d6d8-495a-b85f-6d434a2ea978)
### **Windows 7, Java 8 update 321**

**Comment by BenCheung0422** [comment] 2023-08-27 06:27
Duplicate of #550

**Closed** 2023-10-07 19:31 UTC
Labels: Bug, Duplicate
