### ISSUE TITLE
Only one air wizard ever

### ISSUE THREAD

**Issue by Connie-Dun** [MinicraftPlus/minicraft-plus-revived#407] opened 2022-11-16 02:02 UTC
**Describe the bug**
Defeating the Air Wizard in one save prevents it from spawning in future survival and hardcore mode saves.

**To Reproduce**
1. Defeat the Air Wizard on a save.
2. Create a new world and reach the cloud zone.
3. Press F3 and see there is only one mob - yourself.
4. There is no Air Wizard, making it impossible to unlock the lowest underground level.

**Expected behavior**
Air Wizard should always be present when you first enter the cloud zone.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.1.3

**Additional context**
Does not seem to affect creative mode.

**Comment by Litorom** [comment] 2022-11-27 22:15
I’ve noticed this when a YouTuber played the game, he encountered the same issue. Ended up downgrading.

**Comment by TheBigEye** [comment] 2022-12-02 01:45
**My theory:** there must be a problem with some static variable, since it seems that the value is preserved despite the fact that the game resets the variables when changing worlds.

**Comment by Litorom** [comment] 2022-12-02 12:55
Well it’s fixed in 2.2.0 but should we fix 2.1.0?

**Comment by BenCheung0422** [comment] 2022-12-05 09:44
I think we might not have to?

**Comment by TheBigEye** [comment] 2022-12-23 00:54
Ok, I was testing this thoroughly, apparently the problem is that the `beaten` variable of the AirWizard is `static`:

```java 
public static boolean beaten = false;
```

 So when generating a new world it is not reset and this causes the `checkAirWizard()` method of `level.java` to stop working. (the strange thing is that it has always been static, I don't understand why it started to fail now), this is temporarily solved by assigning `true` to said variable inside the `AirWizard()` constructor ._.

**Comment by Litorom** [comment] 2022-12-23 02:29
Gasp

**Comment by Makkkkus** [comment] 2022-12-23 11:18
Yeah, just don't use static variables.

**Closed** 2023-02-20 12:48 UTC
Labels: Bug, High priority
