### ISSUE TITLE
They should make the mobile version

### ISSUE THREAD

**Issue by ErickN13** [MinicraftPlus/minicraft-plus-revived#571] opened 2023-09-16 15:48 UTC
A very useful thing would be if the MINICRAFT Developers made a Version of the Game for Mobile Devices like Android, IOS, etc. As You Released Minecraft for Many Platforms,I think you can develop Minicraft for many platforms

I've seen DIAF on the Google Play store, but DIAF contains a lot of bugs and a very ugly interface, so it would be cool if they developed an Android version of Minicraft

Who agrees?

**Comment by BenCheung0422** [comment] 2023-09-16 16:27
This is probably a duplicate of #469.

**Comment by mrkash69** [comment] 2023-09-16 18:40
I.

**Comment by Makkkkus** [comment] 2023-09-17 14:02
Duplicate of #469

**Closed** 2023-10-24 04:03 UTC
