### ISSUE TITLE
Black bar

### ISSUE THREAD

**Issue by Goblin464** [MinicraftPlus/minicraft-plus-revived#590] opened 2023-12-10 13:07 UTC
There is always a black bar that shows which item you are holding in hand, even if you are not holding an item in  youre hand.
![Unbenannt](https://github.com/MinicraftPlus/minicraft-plus-revived/assets/150468673/f71748cb-ca9e-432b-a2ec-849fc9fd1ea4)
I think it would be better to only show the black bar when you are holding an item in your hand or even show the item without the black bar.

**Comment by BenCheung0422** [comment] 2024-01-06 10:41
Duplicate of #204

**Closed by BenCheung0422** 2024-01-06 10:41 UTC
Labels: Duplicate, Improvement, Invalid
