### ISSUE TITLE
Canvas initialization error on Java 20 (Linux)

### ISSUE THREAD

**Issue by parkerlreed** [MinicraftPlus/minicraft-plus-revived#540] opened 2023-07-18 21:50 UTC
**Describe the bug**
Crashes on launch 

```
(deck@steamdeck Downloads)$ java -jar minicraft_plus-2.2.0-dev3.jar 
[Crash Handler] ERROR: java.awt.AWTException: Only double or single buffering is supported
        at java.desktop/sun.awt.X11GraphicsConfig.createBackBuffer(X11GraphicsConfig.java:432)
        at java.desktop/sun.awt.X11.XComponentPeer.createBuffers(XComponentPeer.java:1115)
        at java.desktop/java.awt.Component$FlipBufferStrategy.createBuffers(Component.java:4116)
        at java.desktop/java.awt.Component$FlipBufferStrategy.<init>(Component.java:4058)
        at java.desktop/java.awt.Component$FlipSubRegionBufferStrategy.<init>(Component.java:4592)
        at java.desktop/java.awt.Component.createBufferStrategy(Component.java:3921)
        at java.desktop/java.awt.Canvas.createBufferStrategy(Canvas.java:201)
        at minicraft.core.Renderer.initScreen(Renderer.java:114)
        at minicraft.core.Game.main(Game.java:80)
[Crash Handler] ERROR: Crash: Unexpected error: Canvas Initialization Failure: The canvas is unable to be initialized.
(130)(deck@steamdeck Downloads)$ java --version
openjdk 20.0.1 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9)
OpenJDK 64-Bit Server VM (build 20.0.1+9, mixed mode, sharing)
```

**To Reproduce**
1. Run with java -jar minicraft_plus-2.2.0-dev3.jar 

**Expected behavior**
Game running

**Screenshots**
![image](https://github.com/MinicraftPlus/minicraft-plus-revived/assets/841440/85fcd0ee-0e6a-4dcd-adef-cfec90e6ec45)

**Desktop (please complete the following information):**
 - OS: Steam OS 3.5
 - Game version 2.2.0

**Additional context**

**Comment by parkerlreed** [comment] 2023-07-18 21:53
Looks like this was already fixed but there hasn't been a new release?

https://github.com/MinicraftPlus/minicraft-plus-revived/pull/474

**Comment by parkerlreed** [comment] 2023-07-18 21:58
Tried building it manually but get an unsupported class version 64 error

```
(1)(deck@steamdeck minicraft-plus-revived)$ ./gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
Could not open settings generic class cache for settings file '/home/deck/build/minicraft-plus-revived/settings.gradle' (/home/deck/.gradle/caches/7.3/scripts/d8w0j42yss9vvupod6hmx695x).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 64

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 751ms
```

**Comment by Litorom** [comment] 2023-07-19 01:25
We have nightly builds with the latest fixes and sometimes unstable features. Idk what happened to it however.

**Comment by Makkkkus** [comment] 2023-07-19 20:59
https://github.com/MinicraftPlus/minicraft-plus-revived/actions/runs/5604020457

Fixed!

**Comment by Makkkkus** [comment] 2023-07-19 21:00
duplicate of #465

**Closed by Makkkkus** 2023-07-19 21:00 UTC
Labels: Bug
