### ISSUE TITLE
Canvas Initialization Failure on macOS Sonoma

### ISSUE THREAD

**Issue by Kurtjwest** [MinicraftPlus/minicraft-plus-revived#576] opened 2023-10-14 03:15 UTC
**Describe the bug**
Minicraft crashes seconds after starting

**To Reproduce**
1. open jar from finder
2. Receive:
"Crash Unexpected Error"
"Canvas Initiation Failure"
"The canvas is unable to be initialized."
"java.awt.AWTException: Only double buffering is supported
	at java.desktop/sun.java2d.metal.MTLGraphicsConfig.assertOperationSupported(MTLGraphicsConfig.java:274)
	at java.desktop/sun.lwawt.LWComponentPeer.createBuffers(LWComponentPeer.java:515)
	at java.desktop/java.awt.Component$FlipBufferStrategy.createBuffers(Component.java:4117)
	at java.desktop/java.awt.Component$FlipBufferStrategy.<init>(Component.java:4059)
	at java.desktop/java.awt.Component$FlipSubRegionBufferStrategy.<init>(Component.java:4593)
	at java.desktop/java.awt.Component.createBufferStrategy(Component.java:3922)
	at java.desktop/java.awt.Canvas.createBufferStrategy(Canvas.java:201)
	at minicraft.core.Renderer.initScreen(Renderer.java:114)
	at minicraft.core.Game.main(Game.java:80)
"

**Expected behavior**
The game to start

**Screenshots**
<img width="859" alt="Screenshot 2023-10-13 at 11 12 21 PM" src="https://github.com/MinicraftPlus/minicraft-plus-revived/assets/34839176/361804c6-773a-4512-a8c5-75290467a07f">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.0
 - Game version: [Version 2.2.0, Pre-Release 3](https://github.com/MinicraftPlus/minicraft-plus-revived/releases/tag/v2.2.0-dev3)

**Comment by Kurtjwest** [comment] 2023-10-14 03:27
when run in terminal it additionally says:
"2023-10-13 23:24:40.482 java[40757:753337] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:."

**Comment by BenCheung0422** [comment] 2023-10-14 11:00
Duplicate of #465

**Closed by BenCheung0422** 2023-10-14 11:00 UTC
Labels: Bug

**Comment by BenCheung0422** [comment] 2023-10-14 11:05
> when run in terminal it additionally says: "2023-10-13 23:24:40.482 java[40757:753337] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:."

For this warning, it is common for all Java applications nowadays on Sonoma 14.

**Comment by BenCheung0422** [comment] 2023-10-14 12:04
There is seemingly no such a solution for languages that are built from C/C++/Objective C suppressing the warning about macOS secure coding. It is currently unresolvable.
